version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: redis-server --appendonly yes
  server:
    image: node
    ports:
      - "3636:3636"
    volumes:
      - ./server:/server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis
  client:
    image: react
    ports:
      - "5173:5173"
    volumes:
      - ./client:/client
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis
